server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate-ddl: true
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: blind3256@!
      jdbc-url: jdbc:h2:./db/eduwill
  h2:
    console:
      enabled: true
logging.level.org.springframework.web.client.RestTemplate: INFO
demo:
  jwt:
    secret: eduwill
#    expire: 60000
    expire: 86400000
